// Demo data for Enquiries table
// Export as a plain array so components can import and manage state locally

// Column definitions for Users table (no React logic)
export const userColumns = [
  { accessorKey: "email", header: "Email" },
  { accessorKey: "phone", header: "Phone" },
  { accessorKey: "student_name", header: "Student Name" },
  { accessorKey: "father_name", header: "Father Name" },
  { accessorKey: "gender", header: "Gender" },
  { accessorKey: "zip_code", header: "Zip Code" },
  { accessorKey: "city", header: "City" },
  { accessorKey: "state", header: "State" },
  { accessorKey: "country", header: "Country" },
  { accessorKey: "instagram_handle", header: "Instagram Handle" },
  { accessorKey: "education_type", header: "Education Type" },
  { accessorKey: "selected_course", header: "Selected Course" },
  { accessorKey: "course_fee", header: "Course Fee" },
  { accessorKey: "discount", header: "Discount" },
  { accessorKey: "payment_type", header: "Payment Type" },
  { accessorKey: "total_payable", header: "Total Payable" },
  { accessorKey: "created_at", header: "Created At" },
  { accessorKey: "last_sign_in", header: "Last Sign In" },
  { accessorKey: "providers", header: "Providers" },
  { accessorKey: "phone_auth_used", header: "Phone Auth Used" },
  { accessorKey: "google_info", header: "Google Info" },
  { accessorKey: "profile", header: "Profile" },
  { accessorKey: "application", header: "Application" },
  { accessorKey: "updated_at", header: "Updated At" },
  { accessorKey: "school_std", header: "School Std" },
  { accessorKey: "board", header: "Board" },
  { accessorKey: "board_year", header: "Board Year" },
  { accessorKey: "school_name", header: "School Name" },
  { accessorKey: "college_name", header: "College Name" },
  { accessorKey: "college_year", header: "College Year" },
  { accessorKey: "diploma_course", header: "Diploma Course" },
  { accessorKey: "diploma_year", header: "Diploma Year" },
  { accessorKey: "diploma_college", header: "Diploma College" },
  { accessorKey: "other_description", header: "Other Description" },
  { accessorKey: "id", header: "ID" },
  { accessorKey: "legacy_external_id", header: "Legacy External ID" },
  { accessorKey: "firebase_uid", header: "Firebase UID" },
  { accessorKey: "nata_attempt_year", header: "NATA Attempt Year" },
  { accessorKey: "username", header: "Username" },
  { accessorKey: "bio", header: "Bio" },
  { accessorKey: "interests", header: "Interests" },
  { accessorKey: "dob", header: "Date of Birth" },
  { accessorKey: "avatar_path", header: "Avatar Path" },
  { accessorKey: "account_type", header: "Account Type" },
  {
    accessorKey: "nata_calculator_sessions",
    header: "NATA Calculator Sessions",
    minWidth: "16.5rem",
  },
];

export const initialUserData = [
  {
    email: "alice@example.com",
    phone: "+1 (555) 123-4567",
    student_name: "Alice Johnson",
    father_name: "Robert Johnson",
    gender: "Female",
    zip_code: "10001",
    city: "New York",
    state: "NY",
    country: "USA",
    instagram_handle: "@alicejohnson",
    education_type: "School",
    selected_course: "Mathematics",
    course_fee: 1200.0,
    discount: 100.0,
    payment_type: "Credit Card",
    total_payable: 1100.0,
    created_at: "2025-09-01T10:00:00Z",
    last_sign_in: "2025-09-15T09:30:00Z",
    providers: ["google"],
    phone_auth_used: true,
    google_info: { email: "alice@gmail.com" },
    profile: { bio: "Math enthusiast" },
    application: { status: "Submitted" },
    updated_at: "2025-09-15T09:30:00Z",
    school_std: "10",
    board: "CBSE",
    board_year: "2025",
    school_name: "Springfield High",
    college_name: "",
    college_year: "",
    diploma_course: "",
    diploma_year: "",
    diploma_college: "",
    other_description: "N/A",
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    legacy_external_id: "ext-001",
    firebase_uid: "firebase-uid-001",
    nata_attempt_year: "2024",
    username: "alicejohnson",
    bio: "Math lover",
    interests: ["math", "science"],
    dob: "2008-05-12",
    avatar_path: "/avatars/alice.png",
    account_type: "Free",
    nata_calculator_sessions: {},
  },
  {
    email: "bob@example.com",
    phone: "+1 (555) 234-5678",
    student_name: "Bob Smith",
    father_name: "John Smith",
    gender: "Male",
    zip_code: "20002",
    city: "Washington",
    state: "DC",
    country: "USA",
    instagram_handle: "@bobsmith",
    education_type: "College",
    selected_course: "Physics",
    course_fee: 1500.0,
    discount: 200.0,
    payment_type: "UPI",
    total_payable: 1300.0,
    created_at: "2025-08-20T11:00:00Z",
    last_sign_in: "2025-09-10T08:45:00Z",
    providers: ["phone"],
    phone_auth_used: false,
    google_info: {},
    profile: { bio: "Physics major" },
    application: { status: "Pending" },
    updated_at: "2025-09-10T08:45:00Z",
    school_std: "",
    board: "",
    board_year: "",
    school_name: "",
    college_name: "Washington College",
    college_year: "2023",
    diploma_course: "",
    diploma_year: "",
    diploma_college: "",
    other_description: "N/A",
    id: "b2c3d4e5-f6a7-8901-bcde-2345678901bc",
    legacy_external_id: "ext-002",
    firebase_uid: "firebase-uid-002",
    nata_attempt_year: "2023",
    username: "bobsmith",
    bio: "Physics lover",
    interests: ["physics", "music"],
    dob: "2006-11-23",
    avatar_path: "/avatars/bob.png",
    account_type: "Paid",
    nata_calculator_sessions: {},
  },
  {
    email: "carol@example.com",
    phone: "+1 (555) 345-6789",
    student_name: "Carol Davis",
    father_name: "Michael Davis",
    gender: "Female",
    zip_code: "30003",
    city: "Chicago",
    state: "IL",
    country: "USA",
    instagram_handle: "@caroldavis",
    education_type: "Diploma",
    selected_course: "Chemistry",
    course_fee: 1400.0,
    discount: 150.0,
    payment_type: "Cash",
    total_payable: 1250.0,
    created_at: "2025-07-15T12:00:00Z",
    last_sign_in: "2025-09-05T10:15:00Z",
    providers: ["email"],
    phone_auth_used: true,
    google_info: {},
    profile: { bio: "Chemistry diploma" },
    application: { status: "Approved" },
    updated_at: "2025-09-05T10:15:00Z",
    school_std: "",
    board: "",
    board_year: "",
    school_name: "",
    college_name: "",
    college_year: "",
    diploma_course: "Chemical Engineering",
    diploma_year: "2022",
    diploma_college: "Chicago Tech",
    other_description: "N/A",
    id: "c3d4e5f6-a7b8-9012-cdef-3456789012cd",
    legacy_external_id: "ext-003",
    firebase_uid: "firebase-uid-003",
    nata_attempt_year: "2022",
    username: "caroldavis",
    bio: "Chemistry fan",
    interests: ["chemistry", "art"],
    dob: "2005-03-18",
    avatar_path: "/avatars/carol.png",
    account_type: "Free",
    nata_calculator_sessions: {},
  },
];
